site_name: Glasses 😎
repo_url: https://github.com/FrancescoSaverioZuppichini/glasses-2.0
edit_uri: edit/main/docs
site_author: Francesco Zuppichini
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
nav:
  - Glasses: index.md
  - Getting Started: getting-started.md
  - Tutorial: tutorial/
  - Contributing: contributing.md
  - Code Reference: reference/
  - Models: models/

plugins:
  - search
  - autorefs
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py #
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      watch:
        - glasses/

markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
extra_css:
  - css/termynal.css

extra_javascript:
  - javascript/termynal.js
  - javascript/custom.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
